# -- Project Information --
title: Project Posts
email: skrillx1300@gmail.com
description: >-
  Haha, funny website description (Insert something swagger here).
twitter_username: Skrillx_13
github_username:  Skrillx13

# -- Build Configuration --
plugins:
  - jekyll-feed