# -- Project Information --
title: Project Posts
email: skrillx1300@gmail.com
description: >-
  Haha, funny website description (Insert something swagger here).

# -- Build Configuration --
plugins:
  - jekyll-feed